
spark-master:
  image: hfreire/hadoop-spark:2.0.2_2.7.2
  labels:
    io.rancher.container.hostname_override: container_name
  external_links:
    - ${hdfs_link}:namenode
  environment:
    - SPARK_LOCAL_IP=0.0.0.0
    - SPARK_PUBLIC_DNS=spark-master
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
  ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
  command: master

spark-slave:
  image: hfreire/hadoop-spark:2.0.2_2.7.2
  labels:
    io.rancher.container.hostname_override: container_name
  external_links:
    - ${hdfs_link}:namenode
  environment:
    - SPARK_LOCAL_IP=0.0.0.0
    - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    - SPARK_CONF_spark_master=spark://spark-master:7077
  ports:
      - "8081:8081"
  command: slave spark://spark-master:7077
