artifactory-server:
  image: docker.bintray.io/jfrog/artifactory-oss:4.14.3
  tty: true
  ports:
    - "8081:8081"
  labels:
    io.rancher.container.hostname_override: container_name
  volume_driver: convoy-nfs
  volumes:
    - artifactory_data:/var/opt/jfrog/artifactory/data
    - artifactory_logs:/var/opt/jfrog/artifactory/logs
    - artifactory_etc:/var/opt/jfrog/artifactory/etc
